from school_domain.api.web.viewsets.school_detail_viewset import SchoolDetailViewSet
from school_domain.api.web.viewsets.department_detail_viewset import DepartmentDetailViewSet
from school_domain.api.web.viewsets.courses_detail_viewset import CoursesDetailViewSet