# Generated by Django 4.0.8 on 2022-12-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('install_ts', models.DateTimeField(auto_now_add=True)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('updated_by_id', models.IntegerField(blank=True, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('type', models.TextField(choices=[('FALL', 'FALL'), ('SPRING', 'SPRING'), ('SUMMER', 'SUMMER'), ('WINTER', 'WINTER')], default='FALL')),
            ],
            options={
                'db_table': 'so_slot',
            },
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['start_time', 'end_time', 'type'], name='so_slot_start_t_5664ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('start_time', 'end_time', 'type')},
        ),
    ]
