# Generated by Django 4.0.8 on 2022-12-21 07:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school_domain', '0003_courses_courses_so_courses_name_7b2512_idx_and_more'),
        ('slot_domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesSlot',
            fields=[
                ('install_ts', models.DateTimeField(auto_now_add=True)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('updated_by_id', models.IntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('planned_capacity', models.BigIntegerField()),
                ('actual_capacity', models.BigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_domain.courses')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot_domain.slot')),
            ],
            options={
                'db_table': 'so_courses_slot',
            },
        ),
        migrations.AddIndex(
            model_name='coursesslot',
            index=models.Index(fields=['courses', 'slot'], name='so_courses__courses_e26392_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursesslot',
            unique_together={('courses', 'slot')},
        ),
    ]
