# Generated by Django 4.0.8 on 2022-12-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('install_ts', models.DateTimeField(auto_now_add=True)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('updated_by_id', models.IntegerField(blank=True, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('college_name', models.TextField()),
                ('type', models.TextField(choices=[('PRIVATE', 'PRIVATE'), ('PUBLIC', 'PUBLIC')], default='PUBLIC')),
                ('meta', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'so_schools',
            },
        ),
        migrations.AddIndex(
            model_name='schools',
            index=models.Index(fields=['id', 'name', 'college_name'], name='so_schools_id_720d72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schools',
            unique_together={('name', 'college_name')},
        ),
    ]
