# Generated by Django 4.0.8 on 2022-12-21 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_domain', '0002_department_remove_schools_so_schools_id_720d72_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('install_ts', models.DateTimeField(auto_now_add=True)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('updated_by_id', models.IntegerField(blank=True, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('schedule', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_domain.department')),
            ],
            options={
                'db_table': 'so_courses',
            },
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['name', 'department'], name='so_courses_name_7b2512_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courses',
            unique_together={('name', 'department')},
        ),
    ]
