# Generated by Django 4.0.8 on 2022-12-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_domain', '0003_courses_courses_so_courses_name_7b2512_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='courses',
            name='so_courses_name_7b2512_idx',
        ),
        migrations.AlterUniqueTogether(
            name='courses',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courses',
            name='code',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='courses',
            unique_together={('name', 'code', 'department')},
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['name', 'code', 'department'], name='so_courses_name_59f8d4_idx'),
        ),
    ]
